#!/usr/bin/env python3
"""Generate compact LaTeX result tables from versioned Monte Carlo summaries."""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd


EFFECT_LABELS = {
    "direct_high": "Direct, high saturation",
    "spillover_control": "Spillover on controls",
}
METHOD_LABELS = {
    "one_bit": "One-bit LDP",
    "laplace": "Laplace LDP",
    "nonprivate": "Nonprivate",
}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--summary", type=Path, default=Path("results/summary/benchmark.csv"))
    parser.add_argument("--output", type=Path, default=Path("paper/generated_results.tex"))
    args = parser.parse_args()
    summary = pd.read_csv(args.summary)
    selected = summary[
        summary["effect"].isin(EFFECT_LABELS)
        & summary["method"].isin(METHOD_LABELS)
        & summary["epsilon"].isin([0.25, 0.5, 1.0])
    ]
    replication_counts = selected["replications"].unique()
    if len(replication_counts) != 1:
        raise ValueError("selected benchmark rows must use one replication count")
    replication_count = int(replication_counts[0])

    lines = [
        "% Generated by scripts/make_tables.py; do not edit by hand.",
        "\\begin{table}[htbp]",
        "\\centering",
        f"\\caption{{Nonlinear benchmark diagnostics from {replication_count} Monte Carlo "
        "replications. Projected RMSE clips only the point estimate to $[-1,1]$; "
        "design-based intervals use unprojected cluster scores. SE/SD is the average "
        "estimated standard error divided by the empirical standard deviation.}",
        "\\label{tab:main}",
        "\\scriptsize",
        "\\resizebox{\\textwidth}{!}{%",
        "\\begin{tabular}{lllrrrrrr}",
        "\\toprule",
        "Effect & $\\epsilon$ & Method & Bias & RMSE & Projected RMSE & SE/SD "
        "& Coverage & Mean length \\\\",
        "\\midrule",
    ]
    for effect in ("direct_high", "spillover_control"):
        rows_to_print = [("nonprivate", 1.0)] + [
            (method, epsilon)
            for epsilon in (0.25, 0.5, 1.0)
            for method in ("one_bit", "laplace")
        ]
        for row_index, (method, epsilon) in enumerate(rows_to_print):
            row = selected[
                (selected["effect"] == effect)
                & (selected["epsilon"] == epsilon)
                & (selected["method"] == method)
            ].iloc[0]
            effect_label = EFFECT_LABELS[effect] if row_index == 0 else ""
            epsilon_label = "--" if method == "nonprivate" else f"{epsilon:g}"
            lines.append(
                f"{effect_label} & {epsilon_label} & {METHOD_LABELS[method]} & "
                f"{row['bias']:+.3f} & {row['rmse']:.3f} & "
                f"{row['projected_rmse']:.3f} & {row['standard_error_ratio']:.2f} & "
                f"{row['coverage']:.3f} & {row['average_interval_length']:.3f} \\\\"
            )
        if effect == "direct_high":
            lines.append("\\addlinespace")
    lines.extend(["\\bottomrule", "\\end{tabular}%", "}", "\\end{table}", ""])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
